# Kubernetes API 버전 및 리소스 종류
apiVersion: v1
kind: Service

# 메타데이터 정의
metadata:
  # Service 이름
  name: {{ include "ml-server-chart.fullname" . }}

  labels: {{- include "ml-server-chart.labels" . | nindent 4 }}

# Service 스펙
spec:
  # Service 타입 (ClusterIP, NodePort, LoadBalancer)
  type: {{ .Values.service.type }}

  # 포트 설정
  ports:
    # Service가 노출할 포트
    - port: {{ .Values.service.port }}
      # Pod의 타겟 포트
      targetPort: http
      # 프로토콜 (TCP, UDP)
      protocol: TCP
      # 포트 이름 (여러 포트 사용 시 구분용)
      name: http

  # Service가 트래픽을 전달할 Pod 선택
  selector: {{- include "ml-server-chart.selectorLabels" . | nindent 4 }}
