# Workflow 이름
name: CI

# 트리거 이벤트
on:
  # main 브랜치에 push될 때
  push:
    branches: [main]
  # main 브랜치로의 PR이 생성/업데이트될 때
  pull_request:
    branches: [main]

# Job 정의
jobs:
  # 테스트 Job
  test:
    # Ubuntu 최신 버전 Runner 사용
    runs-on: ubuntu-latest

    # 빌드 Job (새로 추가)
  build:
    # Ubuntu 최신 Runner
    runs-on: ubuntu-latest
    # test Job이 성공해야 실행
    needs: test

    steps:
      # 저장소 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Python 3.9 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 의존성 캐싱 (선택사항 - 빌드 속도 향상)
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 의존성 설치
      - name: Install dependencies
        run: |
          # pip 업그레이드
          python -m pip install --upgrade pip
          # requirements.txt의 패키지 설치
          pip install -r requirements.txt
          # 테스트용 pytest 설치
          pip install pytest

      # Docker Buildx 설정
      # 멀티 플랫폼 빌드, 빌드 캐시 등 고급 기능 지원
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 짧은 SHA 추출 (앞 7자)
      - name: Extract short SHA
        id: short-sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # Docker 이미지 빌드
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          # 빌드 컨텍스트 - 현재 디렉토리
          context: .
          # Dockerfile 경로 (기본값: ./Dockerfile)
          file: ./Dockerfile
          # 이미지 푸시 여부 (false = 로컬 빌드만)
          push: false
          # 이미지 태그
          tags: |
            ml-server:latest
            ml-server:${{ steps.short-sha.outputs.sha }}
          # 빌드 캐시 활용 (GitHub Actions 캐시 사용)
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 테스트 실행
      - name: Run tests
        run: |
          # pytest로 tests/ 디렉토리의 모든 테스트 실행
          # -v: verbose 모드 (상세한 출력)
          # PYTHONPATH를 현재 디렉토리로 설정하여 app 모듈을 찾을 수 있도록 함
          PYTHONPATH=. pytest tests/ -v

      # 빌드 성공 메시지
      - name: Image built successfully
        run: |
          echo "✅ Docker image built successfully"
          echo "Tags:"
          echo "  - ml-server:latest"
          echo "  - ml-server:${{ steps.short-sha.outputs.sha }}"      
