name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # 테스트 Job (기존과 동일)
  test:
    runs-on: ubuntu-latest

    steps: ...

  # 빌드 Job (새로 추가)
  build:
    # Ubuntu 최신 Runner
    runs-on: ubuntu-latest
    # test Job이 성공해야 실행
    needs: test

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Buildx 설정
      # 멀티 플랫폼 빌드, 빌드 캐시 등 고급 기능 지원
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 짧은 SHA 추출 (앞 7자)
      - name: Extract short SHA
        id: short-sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # Docker 이미지 빌드
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          # 빌드 컨텍스트 - 현재 디렉토리
          context: .
          # Dockerfile 경로 (기본값: ./Dockerfile)
          file: ./Dockerfile
          # 이미지 푸시 여부 (false = 로컬 빌드만)
          push: false
          # 이미지 태그
          tags: |
            ml-server:latest
            ml-server:${{ steps.short-sha.outputs.sha }}
          # 빌드 캐시 활용 (GitHub Actions 캐시 사용)
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 빌드 성공 메시지
      - name: Image built successfully
        run: |
          echo "✅ Docker image built successfully"
          echo "Tags:"
          echo "  - ml-server:latest"
          echo "  - ml-server:${{ steps.short-sha.outputs.sha }}"
